In [5]:
import pandas as pd

df = pd.read_csv('D:\GitHub\TheOX47\Sentiment-Analysis\Data Reporting - Data Set - EN - nps_feedbacks 20230612-12325_en.tsv', delimiter='\t')
df.head()

,nps_score,checkin_date,checkout_date,created_at,source,order_id,hotel_name,pod_type,nps_review,nps_review_en
0,9,2023-06-11 0:00:00,2023-06-12 0:00:00,2023-06-12 1:04:16,iOS,1.011169e+16,Bobobox Tanah Abang,Earth Single,Ok banget,Ok
1,9,2023-06-10 23:00:00,2023-06-11 23:00:00,2023-06-12 1:03:35,iOS,1.023169e+16,Bobocabin Kintamani,Deluxe Cabin,"tempatnya bagus, tenang, nyaman.","The place is good, calm, comfortable."
2,9,2023-06-11 0:00:00,2023-06-12 0:00:00,2023-06-12 0:35:32,Android,1.026169e+16,Bobocabin Baturraden,DELUXE CABIN,OKOK,REASONS
3,10,2023-05-31 0:00:00,2023-06-01 0:00:00,2023-06-11 17:54:34,iOS,1.004169e+16,Bobobox Pancoran,Earth Double,Please improve staff to be more active and dil...,Please improve staff to be more active and dil...
4,10,2023-06-09 0:00:00,2023-06-10 0:00:00,2023-06-11 16:02:58,iOS,1.014169e+16,Bobobox Slamet Riyadi Solo,Sky Double,nice,nice

In [6]:
df[['nps_review', 'nps_review_en']]

,nps_review,nps_review_en
0,Ok banget,Ok
1,"tempatnya bagus, tenang, nyaman.","The place is good, calm, comfortable."
2,OKOK,REASONS
3,Please improve staff to be more active and dil...,Please improve staff to be more active and dil...
4,nice,nice
...,...,...
995,Lokasi berada di tengah kota dan bangunannya k...,The location is in the middle of the city and ...
996,Everything was ok until the last day I was abo...,Everything was ok until the last day I was abo...
997,Oke,Boundary
998,nice,nice
999,Would be better if we can order food/service i...,Would be better if we can order food/service i...

In [7]:
# Fungsi untuk mengidentifikasi kata-kata tidak dikenal
def identify_unknown_words(text, known_words):
    # Tokenisasi kata-kata dalam teks
    words = text.split()

    # Identifikasi kata-kata tidak dikenal
    unknown_words = [word for word in words if word.lower() not in known_words]

    return unknown_words

# Contoh kamus kata-kata yang dikenal (dapat disesuaikan dengan kebutuhan)
known_words = ['yang', 'banyak', 'nyaman', 'pokoknya', 'oke', 'banget']

# Contoh teks dengan kata-kata aneh
example_text = "Tempat ini U bnyk yg nyaman, pokoknya X banget!"

# Identifikasi kata-kata tidak dikenal
unknown_words = identify_unknown_words(example_text, known_words)

# Output hasil identifikasi
print("Teks Asli                :", example_text)
print("Kata-kata Tidak Dikenal:", unknown_words)

Teks Asli                : Tempat ini U bnyk yg nyaman, pokoknya X banget!
Kata-kata Tidak Dikenal: ['Tempat', 'ini', 'U', 'bnyk', 'yg', 'nyaman,', 'X', 'banget!']

In [9]:
import subprocess
import json

def cari_kata_kunci(kata_kunci):
    try:
        # Eksekusi skrip JavaScript menggunakan kbbi.js
        result = subprocess.check_output(['node', '-e', f'const KBBI = require("kbbi.js"); KBBI.cari("{kata_kunci}").then(console.log).catch(console.error);'], text=True)

        # Parsing hasil JSON
        result_json = json.loads(result)
        return result_json
    except Exception as e:
        return {'error': str(e)}

# Contoh penggunaan
kata_kunci = "pohon"
hasil_pencarian = cari_kata_kunci(kata_kunci)
print(hasil_pencarian)

OSError: [Errno 22] Invalid argument: 'D:\\GitHub\\TheOX47\\Sentiment-Analysis\node_modules\\kbbi.js\\src\\kbbi.js'